server:
  port: 8080
  context-path: /admin-server
  
spring:
  mail:
    host: smtp.163.com
    username: jchonker@163.com
    password: jchonker123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            
  boot:
    admin:
      notify:
        mail:
          from: jchonker@163.com
          to: 1843301926@qq.com