server:
  port: 80

spring:
  mail:
    host: smtp.163.com   #163邮箱默认主机不可修改
    username: jchonker@163.com  #邮箱名,要带后缀@163.com
    password: jchonker123   #使用SMTP的授权码作为密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true